// Liste mondiale des pays — auto-générée (FR)
export type WorldCountry = { code: string; name: string; flag: string; dial: string };

export const ALL_COUNTRIES: WorldCountry[] = [
  { code: "AF", name: "Afghanistan", flag: "🇦🇫", dial: "+93" },
  { code: "ZA", name: "Afrique du Sud", flag: "🇿🇦", dial: "+27" },
  { code: "AL", name: "Albanie", flag: "🇦🇱", dial: "+355" },
  { code: "DZ", name: "Algérie", flag: "🇩🇿", dial: "+213" },
  { code: "DE", name: "Allemagne", flag: "🇩🇪", dial: "+49" },
  { code: "AD", name: "Andorre", flag: "🇦🇩", dial: "+376" },
  { code: "AO", name: "Angola", flag: "🇦🇴", dial: "+244" },
  { code: "AG", name: "Antigua-et-Barbuda", flag: "🇦🇬", dial: "+1268" },
  { code: "SA", name: "Arabie saoudite", flag: "🇸🇦", dial: "+966" },
  { code: "AR", name: "Argentine", flag: "🇦🇷", dial: "+54" },
  { code: "AM", name: "Arménie", flag: "🇦🇲", dial: "+374" },
  { code: "AU", name: "Australie", flag: "🇦🇺", dial: "+61" },
  { code: "AT", name: "Autriche", flag: "🇦🇹", dial: "+43" },
  { code: "AZ", name: "Azerbaïdjan", flag: "🇦🇿", dial: "+994" },
  { code: "BS", name: "Bahamas", flag: "🇧🇸", dial: "+1242" },
  { code: "BH", name: "Bahreïn", flag: "🇧🇭", dial: "+973" },
  { code: "BD", name: "Bangladesh", flag: "🇧🇩", dial: "+880" },
  { code: "BB", name: "Barbade", flag: "🇧🇧", dial: "+1246" },
  { code: "BE", name: "Belgique", flag: "🇧🇪", dial: "+32" },
  { code: "BZ", name: "Belize", flag: "🇧🇿", dial: "+501" },
  { code: "BJ", name: "Bénin", flag: "🇧🇯", dial: "+229" },
  { code: "BT", name: "Bhoutan", flag: "🇧🇹", dial: "+975" },
  { code: "BY", name: "Biélorussie", flag: "🇧🇾", dial: "+375" },
  { code: "BO", name: "Bolivie", flag: "🇧🇴", dial: "+591" },
  { code: "BA", name: "Bosnie-Herzégovine", flag: "🇧🇦", dial: "+387" },
  { code: "BW", name: "Botswana", flag: "🇧🇼", dial: "+267" },
  { code: "BR", name: "Brésil", flag: "🇧🇷", dial: "+55" },
  { code: "BN", name: "Brunei", flag: "🇧🇳", dial: "+673" },
  { code: "BG", name: "Bulgarie", flag: "🇧🇬", dial: "+359" },
  { code: "BF", name: "Burkina Faso", flag: "🇧🇫", dial: "+226" },
  { code: "BI", name: "Burundi", flag: "🇧🇮", dial: "+257" },
  { code: "KH", name: "Cambodge", flag: "🇰🇭", dial: "+855" },
  { code: "CM", name: "Cameroun", flag: "🇨🇲", dial: "+237" },
  { code: "CA", name: "Canada", flag: "🇨🇦", dial: "+1" },
  { code: "CV", name: "Cap-Vert", flag: "🇨🇻", dial: "+238" },
  { code: "CF", name: "Centrafrique", flag: "🇨🇫", dial: "+236" },
  { code: "CL", name: "Chili", flag: "🇨🇱", dial: "+56" },
  { code: "CN", name: "Chine", flag: "🇨🇳", dial: "+86" },
  { code: "CY", name: "Chypre", flag: "🇨🇾", dial: "+357" },
  { code: "CO", name: "Colombie", flag: "🇨🇴", dial: "+57" },
  { code: "KM", name: "Comores", flag: "🇰🇲", dial: "+269" },
  { code: "CG", name: "Congo", flag: "🇨🇬", dial: "+242" },
  { code: "KP", name: "Corée du Nord", flag: "🇰🇵", dial: "+850" },
  { code: "KR", name: "Corée du Sud", flag: "🇰🇷", dial: "+82" },
  { code: "CR", name: "Costa Rica", flag: "🇨🇷", dial: "+506" },
  { code: "CI", name: "Côte d'Ivoire", flag: "🇨🇮", dial: "+225" },
  { code: "HR", name: "Croatie", flag: "🇭🇷", dial: "+385" },
  { code: "CU", name: "Cuba", flag: "🇨🇺", dial: "+53" },
  { code: "DK", name: "Danemark", flag: "🇩🇰", dial: "+45" },
  { code: "DJ", name: "Djibouti", flag: "🇩🇯", dial: "+253" },
  { code: "DM", name: "Dominique", flag: "🇩🇲", dial: "+1767" },
  { code: "EG", name: "Égypte", flag: "🇪🇬", dial: "+20" },
  { code: "AE", name: "Émirats arabes unis", flag: "🇦🇪", dial: "+971" },
  { code: "EC", name: "Équateur", flag: "🇪🇨", dial: "+593" },
  { code: "ER", name: "Érythrée", flag: "🇪🇷", dial: "+291" },
  { code: "ES", name: "Espagne", flag: "🇪🇸", dial: "+34" },
  { code: "EE", name: "Estonie", flag: "🇪🇪", dial: "+372" },
  { code: "SZ", name: "Eswatini", flag: "🇸🇿", dial: "+268" },
  { code: "US", name: "États-Unis", flag: "🇺🇸", dial: "+1" },
  { code: "ET", name: "Éthiopie", flag: "🇪🇹", dial: "+251" },
  { code: "FJ", name: "Fidji", flag: "🇫🇯", dial: "+679" },
  { code: "FI", name: "Finlande", flag: "🇫🇮", dial: "+358" },
  { code: "FR", name: "France", flag: "🇫🇷", dial: "+33" },
  { code: "GA", name: "Gabon", flag: "🇬🇦", dial: "+241" },
  { code: "GM", name: "Gambie", flag: "🇬🇲", dial: "+220" },
  { code: "GE", name: "Géorgie", flag: "🇬🇪", dial: "+995" },
  { code: "GH", name: "Ghana", flag: "🇬🇭", dial: "+233" },
  { code: "GI", name: "Gibraltar", flag: "🇬🇮", dial: "+350" },
  { code: "GR", name: "Grèce", flag: "🇬🇷", dial: "+30" },
  { code: "GD", name: "Grenade", flag: "🇬🇩", dial: "+1473" },
  { code: "GL", name: "Groenland", flag: "🇬🇱", dial: "+299" },
  { code: "GP", name: "Guadeloupe", flag: "🇬🇵", dial: "+590" },
  { code: "GT", name: "Guatemala", flag: "🇬🇹", dial: "+502" },
  { code: "GG", name: "Guernesey", flag: "🇬🇬", dial: "+44" },
  { code: "GN", name: "Guinée", flag: "🇬🇳", dial: "+224" },
  { code: "GQ", name: "Guinée équatoriale", flag: "🇬🇶", dial: "+240" },
  { code: "GW", name: "Guinée-Bissau", flag: "🇬🇼", dial: "+245" },
  { code: "GY", name: "Guyana", flag: "🇬🇾", dial: "+592" },
  { code: "GF", name: "Guyane française", flag: "🇬🇫", dial: "+594" },
  { code: "HT", name: "Haïti", flag: "🇭🇹", dial: "+509" },
  { code: "HN", name: "Honduras", flag: "🇭🇳", dial: "+504" },
  { code: "HK", name: "Hong Kong", flag: "🇭🇰", dial: "+852" },
  { code: "HU", name: "Hongrie", flag: "🇭🇺", dial: "+36" },
  { code: "IN", name: "Inde", flag: "🇮🇳", dial: "+91" },
  { code: "ID", name: "Indonésie", flag: "🇮🇩", dial: "+62" },
  { code: "IQ", name: "Irak", flag: "🇮🇶", dial: "+964" },
  { code: "IR", name: "Iran", flag: "🇮🇷", dial: "+98" },
  { code: "IE", name: "Irlande", flag: "🇮🇪", dial: "+353" },
  { code: "IS", name: "Islande", flag: "🇮🇸", dial: "+354" },
  { code: "IL", name: "Israël", flag: "🇮🇱", dial: "+972" },
  { code: "IT", name: "Italie", flag: "🇮🇹", dial: "+39" },
  { code: "JM", name: "Jamaïque", flag: "🇯🇲", dial: "+1876" },
  { code: "JP", name: "Japon", flag: "🇯🇵", dial: "+81" },
  { code: "JE", name: "Jersey", flag: "🇯🇪", dial: "+44" },
  { code: "JO", name: "Jordanie", flag: "🇯🇴", dial: "+962" },
  { code: "KZ", name: "Kazakhstan", flag: "🇰🇿", dial: "+7" },
  { code: "KE", name: "Kenya", flag: "🇰🇪", dial: "+254" },
  { code: "KG", name: "Kirghizistan", flag: "🇰🇬", dial: "+996" },
  { code: "KI", name: "Kiribati", flag: "🇰🇮", dial: "+686" },
  { code: "KW", name: "Koweït", flag: "🇰🇼", dial: "+965" },
  { code: "RE", name: "La Réunion", flag: "🇷🇪", dial: "+262" },
  { code: "LA", name: "Laos", flag: "🇱🇦", dial: "+856" },
  { code: "LS", name: "Lesotho", flag: "🇱🇸", dial: "+266" },
  { code: "LV", name: "Lettonie", flag: "🇱🇻", dial: "+371" },
  { code: "LB", name: "Liban", flag: "🇱🇧", dial: "+961" },
  { code: "LR", name: "Libéria", flag: "🇱🇷", dial: "+231" },
  { code: "LY", name: "Libye", flag: "🇱🇾", dial: "+218" },
  { code: "LI", name: "Liechtenstein", flag: "🇱🇮", dial: "+423" },
  { code: "LT", name: "Lituanie", flag: "🇱🇹", dial: "+370" },
  { code: "LU", name: "Luxembourg", flag: "🇱🇺", dial: "+352" },
  { code: "MO", name: "Macao", flag: "🇲🇴", dial: "+853" },
  { code: "MK", name: "Macédoine du Nord", flag: "🇲🇰", dial: "+389" },
  { code: "MG", name: "Madagascar", flag: "🇲🇬", dial: "+261" },
  { code: "MY", name: "Malaisie", flag: "🇲🇾", dial: "+60" },
  { code: "MW", name: "Malawi", flag: "🇲🇼", dial: "+265" },
  { code: "MV", name: "Maldives", flag: "🇲🇻", dial: "+960" },
  { code: "ML", name: "Mali", flag: "🇲🇱", dial: "+223" },
  { code: "MT", name: "Malte", flag: "🇲🇹", dial: "+356" },
  { code: "MA", name: "Maroc", flag: "🇲🇦", dial: "+212" },
  { code: "MQ", name: "Martinique", flag: "🇲🇶", dial: "+596" },
  { code: "MU", name: "Maurice", flag: "🇲🇺", dial: "+230" },
  { code: "MR", name: "Mauritanie", flag: "🇲🇷", dial: "+222" },
  { code: "YT", name: "Mayotte", flag: "🇾🇹", dial: "+262" },
  { code: "MX", name: "Mexique", flag: "🇲🇽", dial: "+52" },
  { code: "MD", name: "Moldavie", flag: "🇲🇩", dial: "+373" },
  { code: "MC", name: "Monaco", flag: "🇲🇨", dial: "+377" },
  { code: "MN", name: "Mongolie", flag: "🇲🇳", dial: "+976" },
  { code: "ME", name: "Monténégro", flag: "🇲🇪", dial: "+382" },
  { code: "MZ", name: "Mozambique", flag: "🇲🇿", dial: "+258" },
  { code: "MM", name: "Myanmar", flag: "🇲🇲", dial: "+95" },
  { code: "NA", name: "Namibie", flag: "🇳🇦", dial: "+264" },
  { code: "NR", name: "Nauru", flag: "🇳🇷", dial: "+674" },
  { code: "NP", name: "Népal", flag: "🇳🇵", dial: "+977" },
  { code: "NI", name: "Nicaragua", flag: "🇳🇮", dial: "+505" },
  { code: "NE", name: "Niger", flag: "🇳🇪", dial: "+227" },
  { code: "NG", name: "Nigéria", flag: "🇳🇬", dial: "+234" },
  { code: "NO", name: "Norvège", flag: "🇳🇴", dial: "+47" },
  { code: "NC", name: "Nouvelle-Calédonie", flag: "🇳🇨", dial: "+687" },
  { code: "NZ", name: "Nouvelle-Zélande", flag: "🇳🇿", dial: "+64" },
  { code: "OM", name: "Oman", flag: "🇴🇲", dial: "+968" },
  { code: "UG", name: "Ouganda", flag: "🇺🇬", dial: "+256" },
  { code: "UZ", name: "Ouzbékistan", flag: "🇺🇿", dial: "+998" },
  { code: "PK", name: "Pakistan", flag: "🇵🇰", dial: "+92" },
  { code: "PA", name: "Panama", flag: "🇵🇦", dial: "+507" },
  { code: "PG", name: "Papouasie-Nouvelle-Guinée", flag: "🇵🇬", dial: "+675" },
  { code: "PY", name: "Paraguay", flag: "🇵🇾", dial: "+595" },
  { code: "NL", name: "Pays-Bas", flag: "🇳🇱", dial: "+31" },
  { code: "PE", name: "Pérou", flag: "🇵🇪", dial: "+51" },
  { code: "PH", name: "Philippines", flag: "🇵🇭", dial: "+63" },
  { code: "PL", name: "Pologne", flag: "🇵🇱", dial: "+48" },
  { code: "PF", name: "Polynésie française", flag: "🇵🇫", dial: "+689" },
  { code: "PR", name: "Porto Rico", flag: "🇵🇷", dial: "+1787" },
  { code: "PT", name: "Portugal", flag: "🇵🇹", dial: "+351" },
  { code: "QA", name: "Qatar", flag: "🇶🇦", dial: "+974" },
  { code: "CD", name: "RD Congo", flag: "🇨🇩", dial: "+243" },
  { code: "RO", name: "Roumanie", flag: "🇷🇴", dial: "+40" },
  { code: "GB", name: "Royaume-Uni", flag: "🇬🇧", dial: "+44" },
  { code: "RU", name: "Russie", flag: "🇷🇺", dial: "+7" },
  { code: "RW", name: "Rwanda", flag: "🇷🇼", dial: "+250" },
  { code: "KN", name: "Saint-Kitts-et-Nevis", flag: "🇰🇳", dial: "+1869" },
  { code: "SM", name: "Saint-Marin", flag: "🇸🇲", dial: "+378" },
  { code: "VC", name: "Saint-Vincent-et-les-Grenadines", flag: "🇻🇨", dial: "+1784" },
  { code: "LC", name: "Sainte-Lucie", flag: "🇱🇨", dial: "+1758" },
  { code: "SV", name: "Salvador", flag: "🇸🇻", dial: "+503" },
  { code: "WS", name: "Samoa", flag: "🇼🇸", dial: "+685" },
  { code: "ST", name: "Sao Tomé-et-Principe", flag: "🇸🇹", dial: "+239" },
  { code: "SN", name: "Sénégal", flag: "🇸🇳", dial: "+221" },
  { code: "RS", name: "Serbie", flag: "🇷🇸", dial: "+381" },
  { code: "SC", name: "Seychelles", flag: "🇸🇨", dial: "+248" },
  { code: "SL", name: "Sierra Leone", flag: "🇸🇱", dial: "+232" },
  { code: "SG", name: "Singapour", flag: "🇸🇬", dial: "+65" },
  { code: "SK", name: "Slovaquie", flag: "🇸🇰", dial: "+421" },
  { code: "SI", name: "Slovénie", flag: "🇸🇮", dial: "+386" },
  { code: "SO", name: "Somalie", flag: "🇸🇴", dial: "+252" },
  { code: "SD", name: "Soudan", flag: "🇸🇩", dial: "+249" },
  { code: "SS", name: "Soudan du Sud", flag: "🇸🇸", dial: "+211" },
  { code: "LK", name: "Sri Lanka", flag: "🇱🇰", dial: "+94" },
  { code: "SE", name: "Suède", flag: "🇸🇪", dial: "+46" },
  { code: "CH", name: "Suisse", flag: "🇨🇭", dial: "+41" },
  { code: "SR", name: "Suriname", flag: "🇸🇷", dial: "+597" },
  { code: "SY", name: "Syrie", flag: "🇸🇾", dial: "+963" },
  { code: "TJ", name: "Tadjikistan", flag: "🇹🇯", dial: "+992" },
  { code: "TW", name: "Taïwan", flag: "🇹🇼", dial: "+886" },
  { code: "TZ", name: "Tanzanie", flag: "🇹🇿", dial: "+255" },
  { code: "TD", name: "Tchad", flag: "🇹🇩", dial: "+235" },
  { code: "CZ", name: "Tchéquie", flag: "🇨🇿", dial: "+420" },
  { code: "TH", name: "Thaïlande", flag: "🇹🇭", dial: "+66" },
  { code: "TL", name: "Timor oriental", flag: "🇹🇱", dial: "+670" },
  { code: "TG", name: "Togo", flag: "🇹🇬", dial: "+228" },
  { code: "TO", name: "Tonga", flag: "🇹🇴", dial: "+676" },
  { code: "TT", name: "Trinité-et-Tobago", flag: "🇹🇹", dial: "+1868" },
  { code: "TN", name: "Tunisie", flag: "🇹🇳", dial: "+216" },
  { code: "TM", name: "Turkménistan", flag: "🇹🇲", dial: "+993" },
  { code: "TR", name: "Turquie", flag: "🇹🇷", dial: "+90" },
  { code: "TV", name: "Tuvalu", flag: "🇹🇻", dial: "+688" },
  { code: "UA", name: "Ukraine", flag: "🇺🇦", dial: "+380" },
  { code: "UY", name: "Uruguay", flag: "🇺🇾", dial: "+598" },
  { code: "VU", name: "Vanuatu", flag: "🇻🇺", dial: "+678" },
  { code: "VA", name: "Vatican", flag: "🇻🇦", dial: "+379" },
  { code: "VE", name: "Venezuela", flag: "🇻🇪", dial: "+58" },
  { code: "VN", name: "Viêt Nam", flag: "🇻🇳", dial: "+84" },
  { code: "YE", name: "Yémen", flag: "🇾🇪", dial: "+967" },
  { code: "ZM", name: "Zambie", flag: "🇿🇲", dial: "+260" },
  { code: "ZW", name: "Zimbabwe", flag: "🇿🇼", dial: "+263" },
];

export function findCountry(code?: string | null): WorldCountry | undefined {
  if (!code) return undefined;
  return ALL_COUNTRIES.find((c) => c.code === code);
}

const normalize = (s: string) =>
  s.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "");

export function searchCountries(q: string, limit = 8): WorldCountry[] {
  const query = normalize(q.trim());
  if (!query) return [];
  const starts: WorldCountry[] = [];
  const contains: WorldCountry[] = [];
  for (const c of ALL_COUNTRIES) {
    const n = normalize(c.name);
    if (n.startsWith(query) || c.code.toLowerCase().startsWith(query)) starts.push(c);
    else if (n.includes(query)) contains.push(c);
    if (starts.length >= limit) break;
  }
  return [...starts, ...contains].slice(0, limit);
}
