/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as DropshippingRouteImport } from './routes/dropshipping'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CodRouteImport } from './routes/cod'
import { Route as CalculateurRoasRouteImport } from './routes/calculateur-roas'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CodIndexRouteImport } from './routes/cod.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as LegalPrivacyRouteImport } from './routes/legal.privacy'
import { Route as LegalMentionsRouteImport } from './routes/legal.mentions'
import { Route as LegalCookiesRouteImport } from './routes/legal.cookies'
import { Route as LegalCgvRouteImport } from './routes/legal.cgv'
import { Route as LegalCguRouteImport } from './routes/legal.cgu'
import { Route as CodCountryRouteImport } from './routes/cod.$country'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ApiCoachRouteImport } from './routes/api/coach'
import { Route as AffilieCodeRouteImport } from './routes/affilie.$code'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppRoasCalculatorRouteImport } from './routes/_app.roas-calculator'
import { Route as AppProductsRouteImport } from './routes/_app.products'
import { Route as AppPlanRouteImport } from './routes/_app.plan'
import { Route as AppNetodshRouteImport } from './routes/_app.netodsh'
import { Route as AppEntriesRouteImport } from './routes/_app.entries'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppAnalyticsRouteImport } from './routes/_app.analytics'
import { Route as AdminAdminRouteImport } from './routes/_admin.admin'
import { Route as ApiPublicUnitechWebhookRouteImport } from './routes/api/public.unitech-webhook'
import { Route as AdminAdminUsersRouteImport } from './routes/_admin.admin.users'
import { Route as AdminAdminSettingsRouteImport } from './routes/_admin.admin.settings'
import { Route as AdminAdminSecurityRouteImport } from './routes/_admin.admin.security'
import { Route as AdminAdminRevenueRouteImport } from './routes/_admin.admin.revenue'
import { Route as AdminAdminExportRouteImport } from './routes/_admin.admin.export'
import { Route as AdminAdminCommunicationRouteImport } from './routes/_admin.admin.communication'
import { Route as AdminAdminBetaTestersRouteImport } from './routes/_admin.admin.beta-testers'
import { Route as AdminAdminAffiliatesRouteImport } from './routes/_admin.admin.affiliates'
import { Route as ApiPublicShopifyInstallRouteImport } from './routes/api/public/shopify/install'
import { Route as ApiPublicShopifyCallbackRouteImport } from './routes/api/public/shopify/callback'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicHooksShopifySyncRouteImport } from './routes/api/public/hooks/shopify-sync'
import { Route as AdminAdminUsersIdRouteImport } from './routes/_admin.admin.users.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const DropshippingRoute = DropshippingRouteImport.update({
  id: '/dropshipping',
  path: '/dropshipping',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CodRoute = CodRouteImport.update({
  id: '/cod',
  path: '/cod',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculateurRoasRoute = CalculateurRoasRouteImport.update({
  id: '/calculateur-roas',
  path: '/calculateur-roas',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CodIndexRoute = CodIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CodRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalMentionsRoute = LegalMentionsRouteImport.update({
  id: '/legal/mentions',
  path: '/legal/mentions',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalCookiesRoute = LegalCookiesRouteImport.update({
  id: '/legal/cookies',
  path: '/legal/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalCgvRoute = LegalCgvRouteImport.update({
  id: '/legal/cgv',
  path: '/legal/cgv',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalCguRoute = LegalCguRouteImport.update({
  id: '/legal/cgu',
  path: '/legal/cgu',
  getParentRoute: () => rootRouteImport,
} as any)
const CodCountryRoute = CodCountryRouteImport.update({
  id: '/$country',
  path: '/$country',
  getParentRoute: () => CodRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const ApiCoachRoute = ApiCoachRouteImport.update({
  id: '/api/coach',
  path: '/api/coach',
  getParentRoute: () => rootRouteImport,
} as any)
const AffilieCodeRoute = AffilieCodeRouteImport.update({
  id: '/affilie/$code',
  path: '/affilie/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppRoasCalculatorRoute = AppRoasCalculatorRouteImport.update({
  id: '/roas-calculator',
  path: '/roas-calculator',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsRoute = AppProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AppRoute,
} as any)
const AppPlanRoute = AppPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => AppRoute,
} as any)
const AppNetodshRoute = AppNetodshRouteImport.update({
  id: '/netodsh',
  path: '/netodsh',
  getParentRoute: () => AppRoute,
} as any)
const AppEntriesRoute = AppEntriesRouteImport.update({
  id: '/entries',
  path: '/entries',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AdminAdminRoute = AdminAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicUnitechWebhookRoute = ApiPublicUnitechWebhookRouteImport.update({
  id: '/api/public/unitech-webhook',
  path: '/api/public/unitech-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminUsersRoute = AdminAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminSettingsRoute = AdminAdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminSecurityRoute = AdminAdminSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminRevenueRoute = AdminAdminRevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminExportRoute = AdminAdminExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminCommunicationRoute = AdminAdminCommunicationRouteImport.update({
  id: '/communication',
  path: '/communication',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminBetaTestersRoute = AdminAdminBetaTestersRouteImport.update({
  id: '/beta-testers',
  path: '/beta-testers',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminAffiliatesRoute = AdminAdminAffiliatesRouteImport.update({
  id: '/affiliates',
  path: '/affiliates',
  getParentRoute: () => AdminAdminRoute,
} as any)
const ApiPublicShopifyInstallRoute = ApiPublicShopifyInstallRouteImport.update({
  id: '/api/public/shopify/install',
  path: '/api/public/shopify/install',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicShopifyCallbackRoute =
  ApiPublicShopifyCallbackRouteImport.update({
    id: '/api/public/shopify/callback',
    path: '/api/public/shopify/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksShopifySyncRoute =
  ApiPublicHooksShopifySyncRouteImport.update({
    id: '/api/public/hooks/shopify-sync',
    path: '/api/public/hooks/shopify-sync',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminAdminUsersIdRoute = AdminAdminUsersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminAdminUsersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/calculateur-roas': typeof CalculateurRoasRoute
  '/cod': typeof CodRouteWithChildren
  '/contact': typeof ContactRoute
  '/dropshipping': typeof DropshippingRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AdminAdminRouteWithChildren
  '/analytics': typeof AppAnalyticsRoute
  '/dashboard': typeof AppDashboardRoute
  '/entries': typeof AppEntriesRoute
  '/netodsh': typeof AppNetodshRoute
  '/plan': typeof AppPlanRoute
  '/products': typeof AppProductsRoute
  '/roas-calculator': typeof AppRoasCalculatorRoute
  '/settings': typeof AppSettingsRoute
  '/admin/login': typeof AdminLoginRoute
  '/affilie/$code': typeof AffilieCodeRoute
  '/api/coach': typeof ApiCoachRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/cod/$country': typeof CodCountryRoute
  '/legal/cgu': typeof LegalCguRoute
  '/legal/cgv': typeof LegalCgvRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/mentions': typeof LegalMentionsRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/blog/': typeof BlogIndexRoute
  '/cod/': typeof CodIndexRoute
  '/admin/affiliates': typeof AdminAdminAffiliatesRoute
  '/admin/beta-testers': typeof AdminAdminBetaTestersRoute
  '/admin/communication': typeof AdminAdminCommunicationRoute
  '/admin/export': typeof AdminAdminExportRoute
  '/admin/revenue': typeof AdminAdminRevenueRoute
  '/admin/security': typeof AdminAdminSecurityRoute
  '/admin/settings': typeof AdminAdminSettingsRoute
  '/admin/users': typeof AdminAdminUsersRouteWithChildren
  '/api/public/unitech-webhook': typeof ApiPublicUnitechWebhookRoute
  '/admin/users/$id': typeof AdminAdminUsersIdRoute
  '/api/public/hooks/shopify-sync': typeof ApiPublicHooksShopifySyncRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/shopify/callback': typeof ApiPublicShopifyCallbackRoute
  '/api/public/shopify/install': typeof ApiPublicShopifyInstallRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calculateur-roas': typeof CalculateurRoasRoute
  '/contact': typeof ContactRoute
  '/dropshipping': typeof DropshippingRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AdminAdminRouteWithChildren
  '/analytics': typeof AppAnalyticsRoute
  '/dashboard': typeof AppDashboardRoute
  '/entries': typeof AppEntriesRoute
  '/netodsh': typeof AppNetodshRoute
  '/plan': typeof AppPlanRoute
  '/products': typeof AppProductsRoute
  '/roas-calculator': typeof AppRoasCalculatorRoute
  '/settings': typeof AppSettingsRoute
  '/admin/login': typeof AdminLoginRoute
  '/affilie/$code': typeof AffilieCodeRoute
  '/api/coach': typeof ApiCoachRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/cod/$country': typeof CodCountryRoute
  '/legal/cgu': typeof LegalCguRoute
  '/legal/cgv': typeof LegalCgvRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/mentions': typeof LegalMentionsRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/blog': typeof BlogIndexRoute
  '/cod': typeof CodIndexRoute
  '/admin/affiliates': typeof AdminAdminAffiliatesRoute
  '/admin/beta-testers': typeof AdminAdminBetaTestersRoute
  '/admin/communication': typeof AdminAdminCommunicationRoute
  '/admin/export': typeof AdminAdminExportRoute
  '/admin/revenue': typeof AdminAdminRevenueRoute
  '/admin/security': typeof AdminAdminSecurityRoute
  '/admin/settings': typeof AdminAdminSettingsRoute
  '/admin/users': typeof AdminAdminUsersRouteWithChildren
  '/api/public/unitech-webhook': typeof ApiPublicUnitechWebhookRoute
  '/admin/users/$id': typeof AdminAdminUsersIdRoute
  '/api/public/hooks/shopify-sync': typeof ApiPublicHooksShopifySyncRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/shopify/callback': typeof ApiPublicShopifyCallbackRoute
  '/api/public/shopify/install': typeof ApiPublicShopifyInstallRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/calculateur-roas': typeof CalculateurRoasRoute
  '/cod': typeof CodRouteWithChildren
  '/contact': typeof ContactRoute
  '/dropshipping': typeof DropshippingRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_admin/admin': typeof AdminAdminRouteWithChildren
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/entries': typeof AppEntriesRoute
  '/_app/netodsh': typeof AppNetodshRoute
  '/_app/plan': typeof AppPlanRoute
  '/_app/products': typeof AppProductsRoute
  '/_app/roas-calculator': typeof AppRoasCalculatorRoute
  '/_app/settings': typeof AppSettingsRoute
  '/admin/login': typeof AdminLoginRoute
  '/affilie/$code': typeof AffilieCodeRoute
  '/api/coach': typeof ApiCoachRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/cod/$country': typeof CodCountryRoute
  '/legal/cgu': typeof LegalCguRoute
  '/legal/cgv': typeof LegalCgvRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/mentions': typeof LegalMentionsRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/blog/': typeof BlogIndexRoute
  '/cod/': typeof CodIndexRoute
  '/_admin/admin/affiliates': typeof AdminAdminAffiliatesRoute
  '/_admin/admin/beta-testers': typeof AdminAdminBetaTestersRoute
  '/_admin/admin/communication': typeof AdminAdminCommunicationRoute
  '/_admin/admin/export': typeof AdminAdminExportRoute
  '/_admin/admin/revenue': typeof AdminAdminRevenueRoute
  '/_admin/admin/security': typeof AdminAdminSecurityRoute
  '/_admin/admin/settings': typeof AdminAdminSettingsRoute
  '/_admin/admin/users': typeof AdminAdminUsersRouteWithChildren
  '/api/public/unitech-webhook': typeof ApiPublicUnitechWebhookRoute
  '/_admin/admin/users/$id': typeof AdminAdminUsersIdRoute
  '/api/public/hooks/shopify-sync': typeof ApiPublicHooksShopifySyncRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/shopify/callback': typeof ApiPublicShopifyCallbackRoute
  '/api/public/shopify/install': typeof ApiPublicShopifyInstallRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/blog'
    | '/calculateur-roas'
    | '/cod'
    | '/contact'
    | '/dropshipping'
    | '/pricing'
    | '/reset-password'
    | '/sitemap.xml'
    | '/admin'
    | '/analytics'
    | '/dashboard'
    | '/entries'
    | '/netodsh'
    | '/plan'
    | '/products'
    | '/roas-calculator'
    | '/settings'
    | '/admin/login'
    | '/affilie/$code'
    | '/api/coach'
    | '/blog/$slug'
    | '/cod/$country'
    | '/legal/cgu'
    | '/legal/cgv'
    | '/legal/cookies'
    | '/legal/mentions'
    | '/legal/privacy'
    | '/blog/'
    | '/cod/'
    | '/admin/affiliates'
    | '/admin/beta-testers'
    | '/admin/communication'
    | '/admin/export'
    | '/admin/revenue'
    | '/admin/security'
    | '/admin/settings'
    | '/admin/users'
    | '/api/public/unitech-webhook'
    | '/admin/users/$id'
    | '/api/public/hooks/shopify-sync'
    | '/api/public/payments/webhook'
    | '/api/public/shopify/callback'
    | '/api/public/shopify/install'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/calculateur-roas'
    | '/contact'
    | '/dropshipping'
    | '/pricing'
    | '/reset-password'
    | '/sitemap.xml'
    | '/admin'
    | '/analytics'
    | '/dashboard'
    | '/entries'
    | '/netodsh'
    | '/plan'
    | '/products'
    | '/roas-calculator'
    | '/settings'
    | '/admin/login'
    | '/affilie/$code'
    | '/api/coach'
    | '/blog/$slug'
    | '/cod/$country'
    | '/legal/cgu'
    | '/legal/cgv'
    | '/legal/cookies'
    | '/legal/mentions'
    | '/legal/privacy'
    | '/blog'
    | '/cod'
    | '/admin/affiliates'
    | '/admin/beta-testers'
    | '/admin/communication'
    | '/admin/export'
    | '/admin/revenue'
    | '/admin/security'
    | '/admin/settings'
    | '/admin/users'
    | '/api/public/unitech-webhook'
    | '/admin/users/$id'
    | '/api/public/hooks/shopify-sync'
    | '/api/public/payments/webhook'
    | '/api/public/shopify/callback'
    | '/api/public/shopify/install'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_app'
    | '/auth'
    | '/blog'
    | '/calculateur-roas'
    | '/cod'
    | '/contact'
    | '/dropshipping'
    | '/pricing'
    | '/reset-password'
    | '/sitemap.xml'
    | '/_admin/admin'
    | '/_app/analytics'
    | '/_app/dashboard'
    | '/_app/entries'
    | '/_app/netodsh'
    | '/_app/plan'
    | '/_app/products'
    | '/_app/roas-calculator'
    | '/_app/settings'
    | '/admin/login'
    | '/affilie/$code'
    | '/api/coach'
    | '/blog/$slug'
    | '/cod/$country'
    | '/legal/cgu'
    | '/legal/cgv'
    | '/legal/cookies'
    | '/legal/mentions'
    | '/legal/privacy'
    | '/blog/'
    | '/cod/'
    | '/_admin/admin/affiliates'
    | '/_admin/admin/beta-testers'
    | '/_admin/admin/communication'
    | '/_admin/admin/export'
    | '/_admin/admin/revenue'
    | '/_admin/admin/security'
    | '/_admin/admin/settings'
    | '/_admin/admin/users'
    | '/api/public/unitech-webhook'
    | '/_admin/admin/users/$id'
    | '/api/public/hooks/shopify-sync'
    | '/api/public/payments/webhook'
    | '/api/public/shopify/callback'
    | '/api/public/shopify/install'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  BlogRoute: typeof BlogRouteWithChildren
  CalculateurRoasRoute: typeof CalculateurRoasRoute
  CodRoute: typeof CodRouteWithChildren
  ContactRoute: typeof ContactRoute
  DropshippingRoute: typeof DropshippingRoute
  PricingRoute: typeof PricingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AffilieCodeRoute: typeof AffilieCodeRoute
  ApiCoachRoute: typeof ApiCoachRoute
  LegalCguRoute: typeof LegalCguRoute
  LegalCgvRoute: typeof LegalCgvRoute
  LegalCookiesRoute: typeof LegalCookiesRoute
  LegalMentionsRoute: typeof LegalMentionsRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  ApiPublicUnitechWebhookRoute: typeof ApiPublicUnitechWebhookRoute
  ApiPublicHooksShopifySyncRoute: typeof ApiPublicHooksShopifySyncRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  ApiPublicShopifyCallbackRoute: typeof ApiPublicShopifyCallbackRoute
  ApiPublicShopifyInstallRoute: typeof ApiPublicShopifyInstallRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dropshipping': {
      id: '/dropshipping'
      path: '/dropshipping'
      fullPath: '/dropshipping'
      preLoaderRoute: typeof DropshippingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cod': {
      id: '/cod'
      path: '/cod'
      fullPath: '/cod'
      preLoaderRoute: typeof CodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculateur-roas': {
      id: '/calculateur-roas'
      path: '/calculateur-roas'
      fullPath: '/calculateur-roas'
      preLoaderRoute: typeof CalculateurRoasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cod/': {
      id: '/cod/'
      path: '/'
      fullPath: '/cod/'
      preLoaderRoute: typeof CodIndexRouteImport
      parentRoute: typeof CodRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/mentions': {
      id: '/legal/mentions'
      path: '/legal/mentions'
      fullPath: '/legal/mentions'
      preLoaderRoute: typeof LegalMentionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/cookies': {
      id: '/legal/cookies'
      path: '/legal/cookies'
      fullPath: '/legal/cookies'
      preLoaderRoute: typeof LegalCookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/cgv': {
      id: '/legal/cgv'
      path: '/legal/cgv'
      fullPath: '/legal/cgv'
      preLoaderRoute: typeof LegalCgvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/cgu': {
      id: '/legal/cgu'
      path: '/legal/cgu'
      fullPath: '/legal/cgu'
      preLoaderRoute: typeof LegalCguRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cod/$country': {
      id: '/cod/$country'
      path: '/$country'
      fullPath: '/cod/$country'
      preLoaderRoute: typeof CodCountryRouteImport
      parentRoute: typeof CodRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/api/coach': {
      id: '/api/coach'
      path: '/api/coach'
      fullPath: '/api/coach'
      preLoaderRoute: typeof ApiCoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/affilie/$code': {
      id: '/affilie/$code'
      path: '/affilie/$code'
      fullPath: '/affilie/$code'
      preLoaderRoute: typeof AffilieCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/roas-calculator': {
      id: '/_app/roas-calculator'
      path: '/roas-calculator'
      fullPath: '/roas-calculator'
      preLoaderRoute: typeof AppRoasCalculatorRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/products': {
      id: '/_app/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AppProductsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/plan': {
      id: '/_app/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof AppPlanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/netodsh': {
      id: '/_app/netodsh'
      path: '/netodsh'
      fullPath: '/netodsh'
      preLoaderRoute: typeof AppNetodshRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/entries': {
      id: '/_app/entries'
      path: '/entries'
      fullPath: '/entries'
      preLoaderRoute: typeof AppEntriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_admin/admin': {
      id: '/_admin/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAdminRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/unitech-webhook': {
      id: '/api/public/unitech-webhook'
      path: '/api/public/unitech-webhook'
      fullPath: '/api/public/unitech-webhook'
      preLoaderRoute: typeof ApiPublicUnitechWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/admin/users': {
      id: '/_admin/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminAdminUsersRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/settings': {
      id: '/_admin/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminAdminSettingsRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/security': {
      id: '/_admin/admin/security'
      path: '/security'
      fullPath: '/admin/security'
      preLoaderRoute: typeof AdminAdminSecurityRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/revenue': {
      id: '/_admin/admin/revenue'
      path: '/revenue'
      fullPath: '/admin/revenue'
      preLoaderRoute: typeof AdminAdminRevenueRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/export': {
      id: '/_admin/admin/export'
      path: '/export'
      fullPath: '/admin/export'
      preLoaderRoute: typeof AdminAdminExportRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/communication': {
      id: '/_admin/admin/communication'
      path: '/communication'
      fullPath: '/admin/communication'
      preLoaderRoute: typeof AdminAdminCommunicationRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/beta-testers': {
      id: '/_admin/admin/beta-testers'
      path: '/beta-testers'
      fullPath: '/admin/beta-testers'
      preLoaderRoute: typeof AdminAdminBetaTestersRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/affiliates': {
      id: '/_admin/admin/affiliates'
      path: '/affiliates'
      fullPath: '/admin/affiliates'
      preLoaderRoute: typeof AdminAdminAffiliatesRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/api/public/shopify/install': {
      id: '/api/public/shopify/install'
      path: '/api/public/shopify/install'
      fullPath: '/api/public/shopify/install'
      preLoaderRoute: typeof ApiPublicShopifyInstallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/shopify/callback': {
      id: '/api/public/shopify/callback'
      path: '/api/public/shopify/callback'
      fullPath: '/api/public/shopify/callback'
      preLoaderRoute: typeof ApiPublicShopifyCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/shopify-sync': {
      id: '/api/public/hooks/shopify-sync'
      path: '/api/public/hooks/shopify-sync'
      fullPath: '/api/public/hooks/shopify-sync'
      preLoaderRoute: typeof ApiPublicHooksShopifySyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/admin/users/$id': {
      id: '/_admin/admin/users/$id'
      path: '/$id'
      fullPath: '/admin/users/$id'
      preLoaderRoute: typeof AdminAdminUsersIdRouteImport
      parentRoute: typeof AdminAdminUsersRoute
    }
  }
}

interface AdminAdminUsersRouteChildren {
  AdminAdminUsersIdRoute: typeof AdminAdminUsersIdRoute
}

const AdminAdminUsersRouteChildren: AdminAdminUsersRouteChildren = {
  AdminAdminUsersIdRoute: AdminAdminUsersIdRoute,
}

const AdminAdminUsersRouteWithChildren = AdminAdminUsersRoute._addFileChildren(
  AdminAdminUsersRouteChildren,
)

interface AdminAdminRouteChildren {
  AdminAdminAffiliatesRoute: typeof AdminAdminAffiliatesRoute
  AdminAdminBetaTestersRoute: typeof AdminAdminBetaTestersRoute
  AdminAdminCommunicationRoute: typeof AdminAdminCommunicationRoute
  AdminAdminExportRoute: typeof AdminAdminExportRoute
  AdminAdminRevenueRoute: typeof AdminAdminRevenueRoute
  AdminAdminSecurityRoute: typeof AdminAdminSecurityRoute
  AdminAdminSettingsRoute: typeof AdminAdminSettingsRoute
  AdminAdminUsersRoute: typeof AdminAdminUsersRouteWithChildren
}

const AdminAdminRouteChildren: AdminAdminRouteChildren = {
  AdminAdminAffiliatesRoute: AdminAdminAffiliatesRoute,
  AdminAdminBetaTestersRoute: AdminAdminBetaTestersRoute,
  AdminAdminCommunicationRoute: AdminAdminCommunicationRoute,
  AdminAdminExportRoute: AdminAdminExportRoute,
  AdminAdminRevenueRoute: AdminAdminRevenueRoute,
  AdminAdminSecurityRoute: AdminAdminSecurityRoute,
  AdminAdminSettingsRoute: AdminAdminSettingsRoute,
  AdminAdminUsersRoute: AdminAdminUsersRouteWithChildren,
}

const AdminAdminRouteWithChildren = AdminAdminRoute._addFileChildren(
  AdminAdminRouteChildren,
)

interface AdminRouteChildren {
  AdminAdminRoute: typeof AdminAdminRouteWithChildren
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminRoute: AdminAdminRouteWithChildren,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppEntriesRoute: typeof AppEntriesRoute
  AppNetodshRoute: typeof AppNetodshRoute
  AppPlanRoute: typeof AppPlanRoute
  AppProductsRoute: typeof AppProductsRoute
  AppRoasCalculatorRoute: typeof AppRoasCalculatorRoute
  AppSettingsRoute: typeof AppSettingsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppEntriesRoute: AppEntriesRoute,
  AppNetodshRoute: AppNetodshRoute,
  AppPlanRoute: AppPlanRoute,
  AppProductsRoute: AppProductsRoute,
  AppRoasCalculatorRoute: AppRoasCalculatorRoute,
  AppSettingsRoute: AppSettingsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface CodRouteChildren {
  CodCountryRoute: typeof CodCountryRoute
  CodIndexRoute: typeof CodIndexRoute
}

const CodRouteChildren: CodRouteChildren = {
  CodCountryRoute: CodCountryRoute,
  CodIndexRoute: CodIndexRoute,
}

const CodRouteWithChildren = CodRoute._addFileChildren(CodRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  BlogRoute: BlogRouteWithChildren,
  CalculateurRoasRoute: CalculateurRoasRoute,
  CodRoute: CodRouteWithChildren,
  ContactRoute: ContactRoute,
  DropshippingRoute: DropshippingRoute,
  PricingRoute: PricingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AdminLoginRoute: AdminLoginRoute,
  AffilieCodeRoute: AffilieCodeRoute,
  ApiCoachRoute: ApiCoachRoute,
  LegalCguRoute: LegalCguRoute,
  LegalCgvRoute: LegalCgvRoute,
  LegalCookiesRoute: LegalCookiesRoute,
  LegalMentionsRoute: LegalMentionsRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  ApiPublicUnitechWebhookRoute: ApiPublicUnitechWebhookRoute,
  ApiPublicHooksShopifySyncRoute: ApiPublicHooksShopifySyncRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  ApiPublicShopifyCallbackRoute: ApiPublicShopifyCallbackRoute,
  ApiPublicShopifyInstallRoute: ApiPublicShopifyInstallRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
